AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  montycloud-assignmentapp

  Sample SAM Template for uploading images and creating thumbnails

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Deployment stage (e.g., dev, prod)

  BucketNamePrefix:
    Type: String
    Default: my-app-users-s3-bucket
    Description: Prefix for S3 bucket names

Globals:
  Api:
    BinaryMediaTypes:
      - "multipart/form-data"
      - "image/jpeg"
      - "image/png"
      - "image/jpg"
      - "application/json"
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON

Resources:
  ImageUploadFunction:
    Type: AWS::Serverless::Function
    Properties: 
      Handler: app.lambda_handler
      CodeUri: ./src
      Runtime: python3.12
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          BUCKET_NAME: !Sub "${BucketNamePrefix}-${Stage}"
      Policies:
        - S3WritePolicy:
            BucketName: !Sub "${BucketNamePrefix}-${Stage}"
      Events:
        ApiGatewayUpload:
          Type: Api
          Properties:
            Path: /upload
            Method: POST

  ThumbnailTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      MemorySize: 128
      Timeout: 60
      Handler: thumbnail.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          BUCKET_NAME: !Sub "${BucketNamePrefix}-${Stage}"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/ThumbnailTriggerFunction:*
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub arn:aws:s3:::${BucketNamePrefix}-${Stage}/images/*
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - !Sub arn:aws:s3:::${BucketNamePrefix}-${Stage}/thumbnail/*

      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket: !Ref ImageBucket 
            Events:
              - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: images/
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Layers:
        - !Ref PILLayer

  PILLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layer/pillayer/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12

  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketNamePrefix}-${Stage}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  BucketPolicy1:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageBucket
      PolicyDocument:
        Statement:
          - Action: "s3:*"
            Effect: Deny
            Principal: '*'
            Resource:
              - !Sub arn:aws:s3:::${ImageBucket}/*
              - !Sub arn:aws:s3:::${ImageBucket}
            Condition:
              Bool:
                aws:SecureTransport: false
    DependsOn: ImageBucket

Outputs:
  ImageUploadApi:
    Description: "API Gateway endpoint to upload images"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload"

  S3BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref ImageBucket
    Export:
      Name: ImageBucketName
